### ISSUE TITLE
Issues Contact form, reach out to us 

### ISSUE THREAD

**Issue by GrayCodez** [iPFSoftwares/youleadsummit-landingpage#14]
- [x] Text box color change to black currently it is white 

- [x] Make sure it is sending emails to youlead@youlead.africa

**Comment by jestrux** [comment]
@GrayCodez Which text box color, because the approved design says they're white.

<img width="481" alt="Screenshot 2020-10-20 at 07 30 32" src="https://user-images.githubusercontent.com/8426172/96540379-3f409400-12a6-11eb-9f66-9852d4cda07e.png">

**Comment by GrayCodez** [comment]
when you start typing on Message hapo ina kua white
